### ISSUE TITLE
Als gemeente wil ik aan een product één of meer VAC’s (VraagAntwoordCombinaties) koppelen

### ISSUE THREAD

**Issue by Martindebijl** [VNG-Realisatie/producttypecatalogus#24]
...zodat ik completer informatie over een product en klanten beter kan informeren.

_Toelichting
VAC’s zullen in een aparte catalogus/verzameling opgeslagen zijn._

Indiener: vanuit Dimpact-projecten OIP met gemeenten Deventer, Enschede, Groningen, Leeuwarden, Zwolle en vanuit KISS met gemeenten Deventer, Emmen, Enschede, Haarlemmermeer, Kampen, Oost Gelre, Utrecht, Zwolle

**Definition of done**
- [ ] besluit relevant/generiek
- [ ] indien relevant/generiek; besluit verwerken in kernmodel of extensie
- [ ] indien kernmodel; verwerkt in model

**Comment by joeribekker** [comment]
Lijkt op #5

**Comment by Martindebijl** [comment]
Eens, VAC is een aparte registratie. Beide registraties (PDC en VAC) moeten wel gerelateerd zijn c.q. naar elkaar verwijzen.

**Comment by ArjanKloosterboer** [comment]
Besproken op 6-2: vervalt. Dubbel met 5.
