### ISSUE TITLE
Als gemeente wil ik één of meer synoniemen opnemen bij het product, die gebruik kunnen worden bij het doorzoeken van de PDC

### ISSUE THREAD

**Issue by Martindebijl** [VNG-Realisatie/producttypecatalogus#26]
...zodat ik sneller gewenste zoekresultaten krijg.

Indiener: vanuit Dimpact-projecten OIP met gemeenten Deventer, Enschede, Groningen, Leeuwarden, Zwolle en vanuit KISS met gemeenten Deventer, Emmen, Enschede, Haarlemmermeer, Kampen, Oost Gelre, Utrecht, Zwolle

**Definition of done**
- [ ] besluit relevant/generiek
- [ ] indien relevant/generiek; besluit verwerken in kernmodel of extensie
- [ ] indien kernmodel; verwerkt in model

**Comment by joeribekker** [comment]
Ik heb dit opgevoerd als "trefwoorden" om iets breder dan enkel synoniemen te spreken. Ik vind dit ticket daarom **duplicate**.

**Comment by Martindebijl** [comment]
Er zijn ook thesauri (een ander woord voor synoniemenlijst). Ik heb gewerkt met de thesaurus Zorg en Welzijn.  Op zich interessant, want als open data c.q. zonder licentie beschikbaar. Zie hieronder

De Thesaurus Zorg en Welzijn is per 1 oktober overgegaan van Stichting Stimulansz naar [Nictiz](http://www.nictiz.nl/). Nictiz is de kennisorganisatie voor digitale informatievoorziening in de zorg en beheert ook het internationale terminologiestelsel [SNOMED CT](https://nictiz.nl/wat-we-doen/activiteiten/terminologie/snomed/). De TZW is met zijn patiëntvriendelijke termen een mooie aanvulling daarop.

Wat betekent dit nu concreet? Per 1 januari 2023 zal de TZW zonder licentiekosten beschikbaar komen. We blijven daarbij doorgaan met onze tweemaandelijkse updates. Organisaties die bestanden ontvangen, blijven deze op de gebruikelijke manier ontvangen. De volledige online-TZW zal daarnaast ook zonder inlog beschikbaar komen.

Onze nieuwe thesauruspostbus waarop u ons kunt bereiken met vragen over de TZW is [tzw@nictiz.nl](mailto:tzw@nictiz.nl)

**Comment by frankmijn** [comment]
Lijkt me een goede om naar te kijken. Ik denk alleen dat het voor het informatiemodel achter de PDC niet zou moeten uitmaken welke thesauri we eraan willen koppelen. Dan is de vraag of de voorgestelde wijzigingen in #4 je ook in staat stelt om deze thesaurus te koppelen.

**Comment by ArjanKloosterboer** [comment]
Besproken op 6-2: vervalt. Dubbel met 4.
