### ISSUE TITLE
Als gemeente wil ik weten waar we welke informatie in het CIM-model vastleggen en waar extensies nodig zijn

### ISSUE THREAD

**Issue by frankmijn** [VNG-Realisatie/producttypecatalogus#43]
zodat ik weet waar we informatie in het CIM-model kwijt kunnen en waar we extensies nodig hebben

**Definition of done**
- [ ] besluit relevant/generiek
- [ ] indien relevant/generiek; besluit verwerken in kernmodel of extensie
- [ ] indien kernmodel; verwerkt in model

**Comment by Martindebijl** [comment]
Is dit meer/anders dan het goed vastleggen en ontsluiten van de informatiemodellen van het kernmodel en de extensies?

**Comment by ArjanKloosterboer** [comment]
Besproken op 14-2: zie #34

**Comment by frankmijn** [comment]
Inderdaad wat ik bedoelde, kan dus gesloten worden.
